name: PUBLISH DOC
on:
  push:
    branches: [ develop ]
jobs:
  build:
    name: 'production'
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2

      - name: Use Node.js 16
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16'

      - name: 🔨 Install Dependencies
        run: npm i

      - name: 🔨 Build Project
        run: npm run build-doc

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.igordrangel.com.br
          username: catui@igordrangel.com.br
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: './dist/'
          local-dir: './dist/cat-ui/'
          dangerous-clean-slate: true
